name = "fixthevuln-checkout"
main = "cloudflare-worker.js"
compatibility_date = "2024-09-23"

[[r2_buckets]]
binding = "PLANNERS"
bucket_name = "fixthevuln-planners"

[[d1_databases]]
binding = "DB"
database_name = "fixthevuln-errors"
database_id = "b2b404bb-897f-4a54-9331-efe8e5bf2646"
